/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EntradaController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author lucas
 */
public class EntradaView extends javax.swing.JFrame {

    /**
     * Creates new form EntradaView
     */
    String mensagem;
    
    EntradaController controller = new EntradaController(this);
    public EntradaView() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonComum = new javax.swing.JButton();
        jButtonPreferencial = new javax.swing.JButton();
        jButtonMensalista = new javax.swing.JButton();
        jLabelMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VInteligent - Entrada");
        setPreferredSize(new java.awt.Dimension(1300, 787));
        setResizable(false);
        setSize(new java.awt.Dimension(128, 102));

        jButtonComum.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonComum.setText("COMUM");
        jButtonComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComumActionPerformed(evt);
            }
        });

        jButtonPreferencial.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonPreferencial.setText("PREFERENCIAL");
        jButtonPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferencialActionPerformed(evt);
            }
        });

        jButtonMensalista.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonMensalista.setText("MENSALISTA");
        jButtonMensalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMensalistaActionPerformed(evt);
            }
        });

        jLabelMensagem.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelMensagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonComum, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMensalista, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonComum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonMensalista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComumActionPerformed

 try {
    if (controller.alocarVagaComum()) {
        
        
                controller.mensagem("VInteligent",  "Bem Vindo. Retire seu Ticket.", 5);
        
              
                //JOptionPane.showMessageDialog(null, "Bem Vindo. Retire seu Ticket.");
       
        //pausar(5000);
      
           this.dispose();
          
           
           EntradaView main = new EntradaView();
           main.setVisible(true);
           
           
           
           
            } else{
        controller.estacionamentoLotado();
               

                //JOptionPane.showMessageDialog(null, "Desculpe. Nosso estacionamento esta lotado no momento.");

            }

        } catch (SQLException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComumActionPerformed

    private void jButtonPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferencialActionPerformed
 try {
            if(controller.alocarVagaPreferencial()){

                
                
                controller.mensagem("VInteligent",  "Bem Vindo. Retire seu Ticket.", 5);
                //JOptionPane.showMessageDialog(null, "Bem Vindo. Retire seu Ticket.");
       
      
      
           this.dispose();
          
           
           EntradaView main = new EntradaView();
           main.setVisible(true);
           
           
                //JOptionPane.showMessageDialog(null, "Vaga alocada com sucesso.");

            }else{

                
                 controller.mensagem("VInteligent",  "Desculpe. Nosso estacionamento esta lotado no momento. ,"
                         + "Retire o ticket e  Dirija-se para a saida", 5);
                //JOptionPane.showMessageDialog(null, "Desculpe. Nosso estacionamento esta lotado no momento.");

            }

        } catch (SQLException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreferencialActionPerformed

    private void jButtonMensalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMensalistaActionPerformed


   String msg="";
        while ("".equals(msg)){
            msg = JOptionPane.showInputDialog("Digite o seu codigo.");
        }

        

        try {
            if(!controller.clienteExiste(Integer.parseInt(msg))){

                
                controller.mensagem("VInteligent",  "Codigo invalido. Tente novamente.", 5);
                
                //JOptionPane.showMessageDialog(null, "Codigo invalido. Tente novamente.");

            }else{
                if(!controller.liberado(Integer.parseInt(msg))){
                    
                    controller.mensagem("VInteligent", "Desculpe. Por alguma razão, seu acesso como Mensalista encontra-se bloqueado no sistema. Entre pela opção de vaga comum e procure imediatamente pelo administrador do estacionamento.", 5);

                   // JOptionPane.showMessageDialog(null, "Desculpe. Por alguma razão, seu acesso como Mensalista encontra-se bloqueado no sistema. Entre pela opção de vaga comum e procure imediatamente pelo administrador do estacionamento.");

                }else{

                    if(controller.alocarVagaMensalista(Integer.parseInt(msg))){
                   
                        
                        controller.mensagem("VInteligent", "Ola mensalista, seja Bem Vindo. Por favor verifique a vaga indicada logo abaixo. ", 5);
               //JOptionPane.showMessageDialog(null, "Ola mensalista, seja Bem Vindo. Por favor verifique a vaga indicada logo abaixo. ");
       
       // pausar(5000);
      
           this.dispose();
          
           
           EntradaView main = new EntradaView();
           main.setVisible(true);
           
           
                        //JOptionPane.showMessageDialog(null, "Vaga alocada com sucesso.");

                    }else{

                        JOptionPane.showMessageDialog(null, "Desculpe. Nosso estacionamento esta lotado no momento.");

                    }
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EntradaView.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMensalistaActionPerformed

    
       
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaView().setVisible(true);
            }
        });
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    public JLabel getjLabelMensagem() {
        return jLabelMensagem;
    }

    public void setjLabelMensagem(JLabel jLabelMensagem) {
        this.jLabelMensagem = jLabelMensagem;
    }



    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComum;
    private javax.swing.JButton jButtonMensalista;
    private javax.swing.JButton jButtonPreferencial;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonComum() {
        return jButtonComum;
    }

    public void setjButtonComum(JButton jButtonComum) {
        this.jButtonComum = jButtonComum;
    }

    public JButton getjButtonMensalista() {
        return jButtonMensalista;
    }

    public void setjButtonMensalista(JButton jButtonMensalista) {
        this.jButtonMensalista = jButtonMensalista;
    }

    public JButton getjButtonPreferencial() {
        return jButtonPreferencial;
    }

    public void setjButtonPreferencial(JButton jButtonPreferencial) {
        this.jButtonPreferencial = jButtonPreferencial;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }




}
