/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



/**
 *
 * @author lucas
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuCadastrarUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuEstacionamento = new javax.swing.JMenu();
        jMenuItemTelaDeEntrada = new javax.swing.JMenuItem();
        jMenuItemTelaDeSaida = new javax.swing.JMenuItem();
        jMenuItemVagasView = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemReceber = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VInteligent - Menu Principal");

        jMenu2.setText("Cadastro");

        jMenu3.setText("Usuarios");

        jMenuCadastrarUsuario.setText("Cadastrar Usuario");
        jMenuCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCadastrarUsuario);

        jMenuItem1.setText("Editar ou Excluir Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenu2.add(jMenu3);

        jMenu4.setText("Clientes");

        jMenuItemCadastrarCliente.setText("Cadastrar Cliente");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadastrarCliente);

        jMenuItem2.setText("Editar ou Excluir Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenuEstacionamento.setText("Estacionamento");
        jMenuEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstacionamentoActionPerformed(evt);
            }
        });

        jMenuItemTelaDeEntrada.setText("Tela de Entrada");
        jMenuItemTelaDeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaDeEntradaActionPerformed(evt);
            }
        });
        jMenuEstacionamento.add(jMenuItemTelaDeEntrada);

        jMenuItemTelaDeSaida.setText("Tela de Saida");
        jMenuItemTelaDeSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaDeSaidaActionPerformed(evt);
            }
        });
        jMenuEstacionamento.add(jMenuItemTelaDeSaida);

        jMenuItemVagasView.setText("Gerenciar Vagas");
        jMenuItemVagasView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVagasViewActionPerformed(evt);
            }
        });
        jMenuEstacionamento.add(jMenuItemVagasView);

        jMenuBar1.add(jMenuEstacionamento);

        jMenu1.setText("Caixa");

        jMenuItemReceber.setText("Receber");
        jMenuItemReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReceberActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemReceber);

        jMenuItem3.setText("Registro de movimentações");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstacionamentoActionPerformed
     
   

    }//GEN-LAST:event_jMenuEstacionamentoActionPerformed

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
        CadastroClienteView cadastroClienteView = new CadastroClienteView();
        cadastroClienteView.setVisible(true);


    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarUsuarioActionPerformed
   CadastroUsuarioView cadastroView = new CadastroUsuarioView();
            cadastroView.setVisible(true);    }//GEN-LAST:event_jMenuCadastrarUsuarioActionPerformed

    private void jMenuItemTelaDeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaDeEntradaActionPerformed
     EntradaView entradaView = new EntradaView();
        entradaView.setVisible(true);

    }//GEN-LAST:event_jMenuItemTelaDeEntradaActionPerformed

    private void jMenuItemTelaDeSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaDeSaidaActionPerformed
        SaidaView saidaView = new SaidaView();
        saidaView.setVisible(true);

    }//GEN-LAST:event_jMenuItemTelaDeSaidaActionPerformed

    private void jMenuItemVagasViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVagasViewActionPerformed
   VagasView vagasView = new VagasView();
        vagasView.setVisible(true);    }//GEN-LAST:event_jMenuItemVagasViewActionPerformed

    private void jMenuItemReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReceberActionPerformed
        CaixaView caixaView = new CaixaView(); 
        caixaView.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemReceberActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EditarExcluirUsuarioView editarExcluirUsuarioView = new EditarExcluirUsuarioView();
        editarExcluirUsuarioView.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
       
            
        ExcluirEditarClienteView excluirEditarClienteView = new ExcluirEditarClienteView();
        excluirEditarClienteView.setVisible(true);
        
            
            
            
     
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        RegistroCaixaView registroCaixaView = new RegistroCaixaView();
        registroCaixaView.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarUsuario;
    private javax.swing.JMenu jMenuEstacionamento;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemReceber;
    private javax.swing.JMenuItem jMenuItemTelaDeEntrada;
    private javax.swing.JMenuItem jMenuItemTelaDeSaida;
    private javax.swing.JMenuItem jMenuItemVagasView;
    // End of variables declaration//GEN-END:variables
}
